// Generated by gencpp from file demo_2/Num.msg
// DO NOT EDIT!


#ifndef DEMO_2_MESSAGE_NUM_H
#define DEMO_2_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo_2
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : num(0)
    , a(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : num(0)
    , a(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;

   typedef int64_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::demo_2::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo_2::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::demo_2::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::demo_2::Num > NumPtr;
typedef boost::shared_ptr< ::demo_2::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo_2::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo_2::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::demo_2::Num_<ContainerAllocator1> & lhs, const ::demo_2::Num_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::demo_2::Num_<ContainerAllocator1> & lhs, const ::demo_2::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace demo_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::demo_2::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo_2::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_2::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo_2::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_2::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo_2::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo_2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86f7a0ce571960a83de6b6b05c343873";
  }

  static const char* value(const ::demo_2::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86f7a0ce571960a8ULL;
  static const uint64_t static_value2 = 0x3de6b6b05c343873ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo_2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo_2/Num";
  }

  static const char* value(const ::demo_2::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo_2::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
"int64 a\n"
"\n"
;
  }

  static const char* value(const ::demo_2::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo_2::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo_2::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo_2::Num_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_2_MESSAGE_NUM_H
